apiVersion: v1
kind: Service
metadata:
  name: react-go-webapp-backend
spec:
  selector:
    app: react-go-webapp-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
