apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-go-webapp-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: react-go-webapp-backend
  template:
    metadata:
      labels:
        app: react-go-webapp-backend
    spec:
      containers:
      - name: react-go-webapp-backend
        image: maxnickerson/react-go-webapp-backend:1.0.0-102
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
