apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-go-webapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-go-webapp-frontend
  template:
    metadata:
      labels:
        app: react-go-webapp-frontend
    spec:
      containers:
      - name: react-go-webapp-frontend
        image: maxnickerson/react-go-webapp-frontend:{{IMAGE_TAG}}
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
